[package]
name = "luisa_compute_backend_impl"
version = "0.1.0-alpha.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luisa_compute_backend = { path = "../luisa_compute_backend" }
lazy_static = "1.4.0"
libc = "0.2"
libloading = "0.8"
log = "0.4"
embree_sys = { git = "https://github.com/shiinamiyuki/embree-sys", optional = true }
parking_lot = "0.12.1"
rayon = "1.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
libm = "0.2.6"
base64ct = { version = "1.5.0", features = ["alloc"] }
indexmap = "2.0.0"
luisa_compute_api_types = { path = "../luisa_compute_api_types" }
luisa_compute_cpu_kernel_defs = { path = "../luisa_compute_cpu_kernel_defs" }
luisa_compute_ir = { path = "../luisa_compute_ir" }
bumpalo = "3.12.1"
color-eyre = "0.5"
half = { version = "2.3.1", features = [
    "std",
    "serde",
    "num-traits",
    "zerocopy",
] }

[features]
default = ["cpu"]
cpu = ["embree_sys"]
remote = []


[lib]
crate-type = ["cdylib"]
name = "luisa_compute_backend_impl"
