[package]
edition = "2021"
name = "luisa_compute_ir"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
parking_lot = "0.12.1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
bincode = "1.3.3"
luisa_compute_cpu_kernel_defs = {path = "../luisa_compute_cpu_kernel_defs"}
luisa_compute_api_types = {path = "../luisa_compute_api_types"}
base64ct = {version = "1.5.0", features = ["alloc"]}
sha2 = "0.10"
indexmap = "1.9.2"

[build-dependencies]
cbindgen = "0.24.3"

[lib]
crate-type = ["staticlib", "rlib"]
name = "luisa_compute_ir"
